import { defineConfig } from "drizzle-kit";

// Drizzle is used as the typed query layer over the existing better-sqlite3
// connection. Schema is generated by introspecting a fully-migrated database
// (the .sql migration runner in src/server/db/migrate.ts remains the source of
// truth for DDL). Regenerate with: bun run db:pull
export default defineConfig({
  dialect: "sqlite",
  schema: "./src/server/db/schema.ts",
  out: "./.context/drizzle-introspect",
  dbCredentials: { url: ".context/introspect.db" },
});
